builds:
  - main: cmd/justify/main.go
    binary: justify
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64

release:
  github:
    owner: utgwkk
    name: justify
